apiVersion: v1
kind: Service
metadata:
  name: poc-kub-argos
  labels:
    app: poc-kub-argos
spec:
  type: ClusterIP
  selector:
    app: poc-kub-argos
  ports:
    - name: http
      port: 80
      targetPort: 3000
